baseURL = "http://sebfisch.github.io/java-concurrency"
languageCode = "en-us"
title = "Java Concurrency"
publishDir = "docs"
theme = "book"
enableGitInfo = true
disableKinds = ['taxonomy', 'taxonomyTerm']

[params]
  BookSearch = false
  BookComments = false
